Poller/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('auth.urls')),
    path('',include('main.urls'))
]

auth/urls.py
from django.urls import path
from auth import views
urlpatterns = [
    path('login/', views.Login.as_view(), name ='auth_login'),
    path('logout/',views.Logout.as_view(), name='auth_logout')
]

main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from main import views

urlpatterns = [
    path('',views.Index.as_view(), name = 'index'),
    path('question/<slug>',login_required(views.Question.as_view()), name ='question'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    slug = models.SlugField()
    content = models.CharField(max_length=1024)

    def __str__(self):
        return self.content

class Answer(models.Model):
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    choice = models.ForeignKey("Choice", on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete= models.CASCADE)

class Choice(models.Model):
    content = models.CharField(max_length=256)
    question = models.ForeignKey("Question", on_delete=models.CASCADE)

    @property
    def answer_count(self):
        return Answer.objects.filter(
            question = self.question,
            choice = self
        ).count()


    def __str__(self):
        return "{} - {}".format(self.question.content[:70],self.content)

main/forms.py
from django import forms

from main import models

class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ['choice']

main/views.py
from django.http import HttpResponseRedirect
from typing import List
from django.shortcuts import render
from main import models, forms
from django.views.generic import (
    ListView,
    DetailView,
    FormView
)
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
# Create your views here.

class Index(ListView):
    model = models.Question
    template_name = 'main/index.html'


class Question(PermissionRequiredMixin, SingleObjectMixin, FormView):
    model = models.Question
    template_name = 'main/question.html'
    form_class = forms.AnswerForm
    permission_required = 'add_answer'

    def get_context_data(self,**kwargs):
        data = super().get_context_data(**kwargs)
        data['answer'] = models.Answer.objects.get(
            question = self.get_object(),
            user = self.request.user
        )
        return data

    def form_valid(self, form):

        obj = form.save(commit=False)
        obj.question = self.get_object()
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect('/')

    def post(self,request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <title>Poller</title>
</head>
<body>
    {% block content %} {% endblock %}
   
</body>
</html>

templates/main/components/navbar.html
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Poller</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Questions</a></li>
        <li>
          {% if request.user.is_authenticated %}
            <a href="{% url 'auth_logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'auth_login' %}">
              Login
            </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>

templates/main/index.html
{% extends 'base.html' %}

{% block content %}
{% include 'main/components/navbar.html' %}
<div class="container">
    <div class="row">
        <h4>
            Popular questions
        </h4>
    </div>
    <div class="row">
        <div class="col-6">
            {% for question in question_list %}
            <div class="collection">
                <a href="{% url 'question' question.slug %}" class="collection-item">
                    {{question.content}}
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/main/question.html
{% extends 'base.html' %}

{% block content %}
{% include 'main/components/navbar.html' %}

<div class="container">
    <div class="row">
        <h4>
            {{question.content}}
        </h4>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="collection">
                    {% for choice in question.choice_set.all %}
                        <div class="collection-item">        
                            {% if answer %}
                                {{choice.content}} ({{choice.answer_count}})
                                {% if answer.choice.id == choice.id %}
                                    Selected
                                {% endif %}
                            {% else %}
                            <label>
                                <input class="with-gap" name="choice" type="radio" value="{{choice.id}}">
                                <span>
                                    {{choice.content}}
                                </span>
                            </label>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if answer %}
        <div class="row">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Submit
            </button>
        </div>
        {% endif %}
        <div class="row">
            <p class="red">
                <ul>
                    {% for error in forms.error %}
                    <li>
                        {{error}}
                    </li>
                    {% endfor %}
                </ul>
            </p>
        </div>

    </form>
</div>

{% endblock %}